title: VDI Design System Docs Site
description: Guidelines, tools, and best practices, with a focus on Accessibility, Performance and User Experience.
theme: just-the-docs

url:  https://brickvd.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
